name: CI (mono)

on:
  push:
  pull_request:

jobs:
  run-ci:
    name: Run

    runs-on: ubuntu-latest

    strategy:
      matrix:
        mono: [5.0, 5.4, 5.12]

    container:
      image: mono:${{ matrix.mono }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          nuget restore Twingly.Search.sln
          nuget install NUnit.Console -Version 3.9.0 -OutputDirectory packages

      - name: Build project
        run: xbuild /p:Configuration=Release Twingly.Search.sln /v:minimal

      - name: Run tests
        run: mono ./packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Twingly.Search.Tests/bin/Release/Twingly.Search.Tests.dll
