name: CI (windows)

on:
  push:
  pull_request:

jobs:
  run-windows-ci:
    name: Run

    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Install dependencies
        run: |
          nuget restore Twingly.Search.sln
          nuget install NUnit.Console -Version 3.11.1 -OutputDirectory packages

      - name: Build project
        run: msbuild Twingly.Search.sln /p:Configuration=Release

      - name: Run tests
        run: ./packages/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./Twingly.Search.Tests/bin/Release/Twingly.Search.Tests.dll
